app:
    debug: false
    description: DevOps Swiss Army Knife TUI
    name: Swiss Army TUI
    version: 1.0.0
aws:
    config_path: ""
    credentials_path: ""
    default_profile: default
    default_region: eu-central-1
    profiles: {}
logger:
    development: true
    encoding: console
    level: info
    output_paths:
        - swiss-army-tui.log
ui:
    border_style: rounded
    mouse_enabled: true
    refresh_interval: 30
    theme: dark
