app:
  name: "Swiss Army TUI"
  version: "1.0.0"
  description: "DevOps Swiss Army Knife TUI"
  debug: false

aws:
  default_profile: "default"
  default_region: "eu-central-1"
  profiles: {}
  config_path: ""
  credentials_path: ""

ui:
  theme: "dark"
  refresh_interval: 30
  mouse_enabled: true
  border_style: "rounded"

logger:
  level: "info"
  development: true
  encoding: "console"
  # output_paths:
  #   - "stderr"
